// <auto-generated/>
namespace EliteDataRelay.Properties {
    using System;
    using System.Reflection;
    using System.Resources;
    using System.Globalization;

    internal static class Strings {
        private static ResourceManager resourceMan;
        private static CultureInfo resourceCulture;

        internal static ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    resourceMan = new ResourceManager("EliteDataRelay.Properties.Strings", typeof(Strings).GetTypeInfo().Assembly);
                }
                return resourceMan;
            }
        }

        internal static CultureInfo Culture {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        internal static string Diagnostics_Title => ResourceManager.GetString("Diagnostics_Title", resourceCulture) ?? "Diagnostics";
        internal static string Diagnostics_OpenFolder => ResourceManager.GetString("Diagnostics_OpenFolder", resourceCulture) ?? "Open Folder";
        internal static string Diagnostics_ClearLog => ResourceManager.GetString("Diagnostics_ClearLog", resourceCulture) ?? "Clear Log";
        internal static string Diagnostics_Refresh => ResourceManager.GetString("Diagnostics_Refresh", resourceCulture) ?? "Refresh";
        internal static string Settings_AdvancedGroup_Title => ResourceManager.GetString("Settings_AdvancedGroup_Title", resourceCulture) ?? "Advanced";
        internal static string Settings_FastStart_Label => ResourceManager.GetString("Settings_FastStart_Label", resourceCulture) ?? "Fast start: skip journal history at startup";
        internal static string Settings_VerboseLogging_Label => ResourceManager.GetString("Settings_VerboseLogging_Label", resourceCulture) ?? "Enable verbose logging";
        internal static string Settings_OpenDiagnostics_Button => ResourceManager.GetString("Settings_OpenDiagnostics_Button", resourceCulture) ?? "Open Diagnostics...";
        internal static string Settings_Localization_GroupTitle => ResourceManager.GetString("Settings_Localization_GroupTitle", resourceCulture) ?? "Localization";
        internal static string Settings_Localization_LanguageLabel => ResourceManager.GetString("Settings_Localization_LanguageLabel", resourceCulture) ?? "Language";
        internal static string Settings_Localization_RestartNote => ResourceManager.GetString("Settings_Localization_RestartNote", resourceCulture) ?? "Language updated. Some texts will update after restart.";
        internal static string Settings_Title => ResourceManager.GetString("Settings_Title", resourceCulture) ?? "Settings";
        internal static string Settings_Subtitle => ResourceManager.GetString("Settings_Subtitle", resourceCulture) ?? "Customize your experience";
        internal static string Settings_Save => ResourceManager.GetString("Settings_Save", resourceCulture) ?? "Save";
        internal static string Settings_Cancel => ResourceManager.GetString("Settings_Cancel", resourceCulture) ?? "Cancel";
        internal static string Settings_Nav_General => ResourceManager.GetString("Settings_Nav_General", resourceCulture) ?? "General";
        internal static string Settings_Nav_Overlay => ResourceManager.GetString("Settings_Nav_Overlay", resourceCulture) ?? "Overlay";
        internal static string Settings_Nav_Hotkeys => ResourceManager.GetString("Settings_Nav_Hotkeys", resourceCulture) ?? "Hotkeys";
        internal static string Settings_Nav_Advanced => ResourceManager.GetString("Settings_Nav_Advanced", resourceCulture) ?? "Advanced";
        internal static string Settings_Nav_Localization => ResourceManager.GetString("Settings_Nav_Localization", resourceCulture) ?? "Localization";
        internal static string App_Title => ResourceManager.GetString("App_Title", resourceCulture) ?? "Elite Data Relay";
        internal static string Common_OK => ResourceManager.GetString("Common_OK", resourceCulture) ?? "OK";
        internal static string Common_Error => ResourceManager.GetString("Common_Error", resourceCulture) ?? "Error";
        internal static string Common_Copied => ResourceManager.GetString("Common_Copied", resourceCulture) ?? "Copied to clipboard!";
        internal static string Error_OpenUrlFormat => ResourceManager.GetString("Error_OpenUrlFormat", resourceCulture) ?? "Failed to open URL: {0}";
        internal static string About_WindowTitle => ResourceManager.GetString("About_WindowTitle", resourceCulture) ?? "About Elite Data Relay";
        internal static string About_VersionLabel => ResourceManager.GetString("About_VersionLabel", resourceCulture) ?? "Version";
        internal static string About_VersionNotFound => ResourceManager.GetString("About_VersionNotFound", resourceCulture) ?? "Version not found";
        internal static string About_ViewProject => ResourceManager.GetString("About_ViewProject", resourceCulture) ?? "View Project on GitHub";
        internal static string About_Description => ResourceManager.GetString("About_Description", resourceCulture) ?? "Windows companion for Elite Dangerous...";
        internal static string Exploration_VisitedSystems_Header => ResourceManager.GetString("Exploration_VisitedSystems_Header", resourceCulture) ?? "VISITED SYSTEMS";
        internal static string Exploration_SelectSystem => ResourceManager.GetString("Exploration_SelectSystem", resourceCulture) ?? "Select a system to view details";
        internal static string Exploration_Col_SystemName => ResourceManager.GetString("Exploration_Col_SystemName", resourceCulture) ?? "System Name";
        internal static string Exploration_Col_Bodies => ResourceManager.GetString("Exploration_Col_Bodies", resourceCulture) ?? "Bodies";
        internal static string Exploration_Col_LastVisit => ResourceManager.GetString("Exploration_Col_LastVisit", resourceCulture) ?? "Last Visit";
        internal static string Exploration_Col_BodyName => ResourceManager.GetString("Exploration_Col_BodyName", resourceCulture) ?? "Body Name";
        internal static string Exploration_Col_Type => ResourceManager.GetString("Exploration_Col_Type", resourceCulture) ?? "Type";
        internal static string Exploration_Col_Distance => ResourceManager.GetString("Exploration_Col_Distance", resourceCulture) ?? "Distance";
        internal static string Exploration_Col_Status => ResourceManager.GetString("Exploration_Col_Status", resourceCulture) ?? "Status";
        internal static string Exploration_Status_Scanned => ResourceManager.GetString("Exploration_Status_Scanned", resourceCulture) ?? "Scanned";
        internal static string Exploration_Status_Mapped => ResourceManager.GetString("Exploration_Status_Mapped", resourceCulture) ?? "Mapped";
        internal static string Exploration_Status_FirstDiscovery => ResourceManager.GetString("Exploration_Status_FirstDiscovery", resourceCulture) ?? "First Discovery";
        internal static string Exploration_Status_FirstFootfall => ResourceManager.GetString("Exploration_Status_FirstFootfall", resourceCulture) ?? "First Footfall!";
        internal static string Exploration_Status_Known => ResourceManager.GetString("Exploration_Status_Known", resourceCulture) ?? "Known";
        internal static string Exploration_History_Empty => ResourceManager.GetString("Exploration_History_Empty", resourceCulture) ?? "EXPLORATION HISTORY: No data yet - start monitoring and scan some systems!";
        internal static string Exploration_History_StatsFormat => ResourceManager.GetString("Exploration_History_StatsFormat", resourceCulture) ?? "EXPLORATION HISTORY: {0}";
        internal static string Overlay_NoSystemData => ResourceManager.GetString("Overlay_NoSystemData", resourceCulture) ?? "NO SYSTEM DATA";
        internal static string Overlay_FSS_ProgressFormat => ResourceManager.GetString("Overlay_FSS_ProgressFormat", resourceCulture) ?? "FSS:     {0:F1}%";
        internal static string Overlay_FSS_CompleteFormat => ResourceManager.GetString("Overlay_FSS_CompleteFormat", resourceCulture) ?? "FSS:     Complete ({0} bodies)";
        internal static string Overlay_ScannedFormatWithTotal => ResourceManager.GetString("Overlay_ScannedFormatWithTotal", resourceCulture) ?? "Scanned: {0} / {1}";
        internal static string Overlay_ScannedFormat => ResourceManager.GetString("Overlay_ScannedFormat", resourceCulture) ?? "Scanned: {0}";
        internal static string Overlay_MappedFormat => ResourceManager.GetString("Overlay_MappedFormat", resourceCulture) ?? "Mapped:  {0}";
        internal static string Overlay_KnownSystem => ResourceManager.GetString("Overlay_KnownSystem", resourceCulture) ?? "Known System";
        internal static string Overlay_SessionFormat => ResourceManager.GetString("Overlay_SessionFormat", resourceCulture) ?? "Session: {0} systems";
        internal static string Overlay_ScansLabel => ResourceManager.GetString("Overlay_ScansLabel", resourceCulture) ?? "{0} scans";
        internal static string Overlay_MappedLabel => ResourceManager.GetString("Overlay_MappedLabel", resourceCulture) ?? "{0} mapped";
        internal static string Tray_Minimized => ResourceManager.GetString("Tray_Minimized", resourceCulture) ?? "Minimized to tray.";
    }
}
